### ISSUE TITLE
side panel ? 

### ISSUE THREAD

**Issue by luluperet** [vatlab/jupyterlab-sos#25]
hello,the side panel will come ?

**Comment by BoPeng** [comment]
The [PR for sidepanel](https://github.com/jupyterlab/jupyterlab/pull/4879) is currently pending. You can perhaps comment on the thread and show your support there.

**Comment by BoPeng** [comment]
I have released jupyterlab-sos 0.4.1 that makes use of the latest feature of JupyterLab that outputs transient information to the console window of notebooks. Basically, you will need to

1. install JupyterLab [1.0.0 alpha 3](https://pypi.org/project/jupyterlab/1.0.0a1/) (or JupyterLab >= 1.0 later)
2. install `jupyterlab-sos` from the package manager
3. Right click a SoS notebook to open a console window, move it to the side if you prefer.
4. Right click "Show Transient Message" to enable transient messages.
5. Now, if you run

```
%run
[1]
[2]
```
or
```
%preview a
a=1
```

the progress or preview information will be sent to the console panel.

**Comment by BoPeng** [comment]
I have pushed the latest version to our live server so that you can test this feature by clicking [this link](http://128.135.144.117:8000/hub/user-redirect/lab).

**Comment by j-andrews7** [comment]
Is this usable with `%toc`? It doesn't seem to yield anything for me. Or does JupyterLab have another ToC-like function available? I am trying to make the transition and that's probably the most inconvenient thing so far.

Sorry if this is mentioned elsewhere, I tried a search through issues and didn't see anything specific and didn't think it warranted its own issue.

**Comment by BoPeng** [comment]
Yes, jupyterlab-toc is the one I am using right now, and I would love to see it included in the core. That is a full-functional toc widget so there is no point of using `%toc` for it. 

We also had used `%toc -n` to generate a TOC in the notebook, but the new (ish) templates with auto-generated TOC (e.g. [`sos-report-toc`](https://github.com/vatlab/sos-notebook/tree/master/src/sos_notebook/templates)) works much better.

So in the end I may just remove this magic.

**Comment by gaow** [comment]
>  jupyterlab-toc is the one I am using right now, and I would love to see it included in the core. 

I just upgraded to JupyterLab 1.0.0. To add to this: 

1. at this piont, `jupyter labextension install jupyterlab-toc` does not work but `jupyter labextension install @jupyterlab/toc` does -- @BoPeng is that the reason you did not include this line to README.md? Should we do it now or later?
2. The live server side panel still does not have TOC -- I guess we can add it later when we upgrade the software versions.

**Comment by BoPeng** [comment]
I did not include instruction about the TOC extension because it is technically not related to our extension, and I do not want our README to become obsolete after the extension is changed (e.g. merged to the core). I have learned the lesson by including instruction for kernel installation to SoS Notebook, only to find that our instructions stopped working after upstream changes.

Yes we can add that later, and even make the lab version the default.
